In [6]:
pip install pandas
pip install numpy
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [79]:
pip install joblib

Note: you may need to restart the kernel to use updated packages.


In [80]:
import joblib as jb

In [4]:
import pandas as pd
import numpy as np

In [8]:
df=pd.read_csv(r"C:\Users\user\Downloads\archive\neo.csv")

In [16]:
df.head(7)

id                 name  est_diameter_min  est_diameter_max  \
0   2162635  162635 (2000 SS164)          1.198271          2.679415   
1   2277475    277475 (2005 WK4)          0.265800          0.594347   
2   2512244   512244 (2015 YE18)          0.722030          1.614507   
3   3596030          (2012 BV13)          0.096506          0.215794   
4   3667127          (2014 GE35)          0.255009          0.570217   
5  54138696          (2021 GY23)          0.036354          0.081291   
6  54189957          (2021 PY40)          0.171615          0.383743   

   relative_velocity  miss_distance orbiting_body  sentry_object  \
0       13569.249224   5.483974e+07         Earth          False   
1       73588.726663   6.143813e+07         Earth          False   
2      114258.692129   4.979872e+07         Earth          False   
3       24764.303138   2.543497e+07         Earth          False   
4       42737.733765   4.627557e+07         Earth          False   
5       34297.587778   4.058569e+07         Earth          False   
6       27529.472307   2.906912e+07         Earth          False   

   absolute_magnitude  hazardous  
0               16.73      False  
1               20.00       True  
2               17.83      False  
3               22.20      False  
4               20.09       True  
5               24.32      False  
6               20.95      False

In [47]:
df["hazardous"].value_counts()

False    81996
True      8840
Name: hazardous, dtype: int64

id , name , orbiting_body , sentry_object ---->Drop

In [22]:
np.min(df["est_diameter_min"])

0.0006089126

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90836 entries, 0 to 90835
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   id                  90836 non-null  int64  
 1   name                90836 non-null  object 
 2   est_diameter_min    90836 non-null  float64
 3   est_diameter_max    90836 non-null  float64
 4   relative_velocity   90836 non-null  float64
 5   miss_distance       90836 non-null  float64
 6   orbiting_body       90836 non-null  object 
 7   sentry_object       90836 non-null  bool   
 8   absolute_magnitude  90836 non-null  float64
 9   hazardous           90836 non-null  bool   
dtypes: bool(2), float64(5), int64(1), object(2)
memory usage: 5.7+ MB


In [25]:
df.describe()

id  est_diameter_min  est_diameter_max  relative_velocity  \
count  9.083600e+04      90836.000000      90836.000000       90836.000000   
mean   1.438288e+07          0.127432          0.284947       48066.918918   
std    2.087202e+07          0.298511          0.667491       25293.296961   
min    2.000433e+06          0.000609          0.001362         203.346433   
25%    3.448110e+06          0.019256          0.043057       28619.020645   
50%    3.748362e+06          0.048368          0.108153       44190.117890   
75%    3.884023e+06          0.143402          0.320656       62923.604633   
max    5.427591e+07         37.892650         84.730541      236990.128088   

       miss_distance  absolute_magnitude  
count   9.083600e+04        90836.000000  
mean    3.706655e+07           23.527103  
std     2.235204e+07            2.894086  
min     6.745533e+03            9.230000  
25%     1.721082e+07           21.340000  
50%     3.784658e+07           23.700000  
75%     5.654900e+07           25.700000  
max     7.479865e+07           33.200000

In [28]:
df.drop(columns=["id","name","orbiting_body","sentry_object"],inplace=True)

In [29]:
df.head()

est_diameter_min  est_diameter_max  relative_velocity  miss_distance  \
0          1.198271          2.679415       13569.249224   5.483974e+07   
1          0.265800          0.594347       73588.726663   6.143813e+07   
2          0.722030          1.614507      114258.692129   4.979872e+07   
3          0.096506          0.215794       24764.303138   2.543497e+07   
4          0.255009          0.570217       42737.733765   4.627557e+07   

   absolute_magnitude  hazardous  
0               16.73      False  
1               20.00       True  
2               17.83      False  
3               22.20      False  
4               20.09       True

In [31]:
X=df.drop(columns=["hazardous"])
y=df["hazardous"]

In [32]:
X.head()

est_diameter_min  est_diameter_max  relative_velocity  miss_distance  \
0          1.198271          2.679415       13569.249224   5.483974e+07   
1          0.265800          0.594347       73588.726663   6.143813e+07   
2          0.722030          1.614507      114258.692129   4.979872e+07   
3          0.096506          0.215794       24764.303138   2.543497e+07   
4          0.255009          0.570217       42737.733765   4.627557e+07   

   absolute_magnitude  
0               16.73  
1               20.00  
2               17.83  
3               22.20  
4               20.09

In [58]:
# x-min/max-min
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
X=mms.fit_transform(X)
X

array([[3.16072151e-02, 3.16072151e-02, 5.64469972e-02, 7.33140811e-01,
        3.12891114e-01],
       [6.99859604e-03, 6.99859603e-03, 3.09921777e-01, 8.21364026e-01,
        4.49311640e-01],
       [1.90388437e-02, 1.90388437e-02, 4.81679530e-01, 6.65740213e-01,
        3.58781811e-01],
       ...,
       [8.27278640e-04, 8.27278640e-04, 3.10974339e-02, 3.79640314e-01,
        6.41218189e-01],
       [1.77130266e-04, 1.77130265e-04, 2.91383698e-01, 9.18352249e-01,
        7.74718398e-01],
       [1.03590911e-03, 1.03590911e-03, 1.13271142e-01, 7.99088943e-01,
        6.21193158e-01]])

In [33]:
y.head()

0    False
1     True
2    False
3    False
4     True
Name: hazardous, dtype: bool

In [60]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test=train_test_split(X,y,train_size=0.8,random_state=45)
X_train

array([[7.98719342e-05, 7.98719338e-05, 3.96590905e-01, 2.38542697e-03,
        8.38130997e-01],
       [2.10232551e-03, 2.10232551e-03, 3.11189586e-01, 5.50697588e-01,
        5.57780559e-01],
       [1.06010565e-02, 1.06010565e-02, 2.95831790e-01, 5.45837353e-01,
        4.11764706e-01],
       ...,
       [1.82897540e-03, 1.82897540e-03, 2.42725478e-01, 5.61767404e-01,
        5.70296204e-01],
       [4.26525814e-04, 4.26525814e-04, 1.46412606e-01, 2.22046830e-01,
        6.99624531e-01],
       [9.52223747e-04, 9.52223746e-04, 2.06970096e-01, 5.01739747e-01,
        6.28702545e-01]])

In [61]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [62]:
lr

LogisticRegression()

In [63]:
lr.fit(X_train,y_train)

LogisticRegression()

In [64]:
y_pred=lr.predict(X_test)

In [65]:
y_pred[:5]

array([False, False, False, False, False])

In [66]:
y_test[:5]

15924    False
67582    False
27973    False
88527    False
89445    False
Name: hazardous, dtype: bool

In [68]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[16116,  1683],
       [  243,   126]], dtype=int64)

In [69]:
lr.score(X_test,y_test)

0.8939894319682959

In [48]:
# true positive true said true ,false positive false said true,true negative true said false,false negative False said false

In [70]:
df2=pd.read_csv(r"C:\Users\user\Downloads\archive\neo_v2.csv")
df2.head()

id                 name  est_diameter_min  est_diameter_max  \
0  2162635  162635 (2000 SS164)          1.198271          2.679415   
1  2277475    277475 (2005 WK4)          0.265800          0.594347   
2  2512244   512244 (2015 YE18)          0.722030          1.614507   
3  3596030          (2012 BV13)          0.096506          0.215794   
4  3667127          (2014 GE35)          0.255009          0.570217   

   relative_velocity  miss_distance orbiting_body  sentry_object  \
0       13569.249224   5.483974e+07         Earth          False   
1       73588.726663   6.143813e+07         Earth          False   
2      114258.692129   4.979872e+07         Earth          False   
3       24764.303138   2.543497e+07         Earth          False   
4       42737.733765   4.627557e+07         Earth          False   

   absolute_magnitude  hazardous  
0               16.73      False  
1               20.00       True  
2               17.83      False  
3               22.20      False  
4               20.09       True

In [71]:
df2.drop(columns=["id","name","orbiting_body","sentry_object"],inplace=True)

In [72]:
df2.head()

est_diameter_min  est_diameter_max  relative_velocity  miss_distance  \
0          1.198271          2.679415       13569.249224   5.483974e+07   
1          0.265800          0.594347       73588.726663   6.143813e+07   
2          0.722030          1.614507      114258.692129   4.979872e+07   
3          0.096506          0.215794       24764.303138   2.543497e+07   
4          0.255009          0.570217       42737.733765   4.627557e+07   

   absolute_magnitude  hazardous  
0               16.73      False  
1               20.00       True  
2               17.83      False  
3               22.20      False  
4               20.09       True

In [73]:
X2=df2.drop(columns=["hazardous"])
y2=df2["hazardous"]

In [74]:
X2=mms.transform(X2)
X2

array([[3.16072151e-02, 3.16072151e-02, 5.64469972e-02, 7.33140811e-01,
        3.12891114e-01],
       [6.99859604e-03, 6.99859603e-03, 3.09921777e-01, 8.21364026e-01,
        4.49311640e-01],
       [1.90388437e-02, 1.90388437e-02, 4.81679530e-01, 6.65740213e-01,
        3.58781811e-01],
       ...,
       [8.27278640e-04, 8.27278640e-04, 3.10974339e-02, 3.79640314e-01,
        6.41218189e-01],
       [1.77130266e-04, 1.77130265e-04, 2.91383698e-01, 9.18352249e-01,
        7.74718398e-01],
       [1.03590911e-03, 1.03590911e-03, 1.13271142e-01, 7.99088943e-01,
        6.21193158e-01]])

In [75]:
v2pred=lr.predict(X2)
v2pred

array([False, False,  True, ..., False, False, False])

In [76]:
confusion_matrix(v2pred,y2)

array([[80832,  8247],
       [ 1164,   593]], dtype=int64)

In [77]:
lr.score(X2,y2)

0.8963957021445242

In [ ]:
jb.dump(lr,"")